function res = pcg_fun_nuisance(x,proj_id,invChol_Array,L,reg_param)

%This function will evaluate matrix-vector product of ATA+reg_param L = (RA)^T(RA) =
%A^T R^T R A. A is the system matrix and R is the inverse cholesky
%factorization of the model error.

%INPUT
%A: System matrix generated by ASTRA
%reg_param: Regularization parameter
%L: Gaussian Prior matrix

%OUTPUT
%res: (A^T R^T R A + reg_param L) x

[~,rays,n_proj] = size(invChol_Array);

N = sqrt(length(x));
[~,forward_proj] = astra_create_sino(reshape(x,N,N),proj_id);
Ax = reshape(forward_proj,n_proj*rays,1);

tmp_1 = Rmult(Ax,invChol_Array);
tmp_2 = reshape(Rmult_T(tmp_1,invChol_Array),n_proj,rays);

[~,back_proj] = astra_create_backprojection(tmp_2,proj_id);

res = reshape(back_proj,N^2,1);

res = res + reg_param*L*x;
end
